export { RegisterPage } from './RegisterPage';
export { LoginPage } from './LoginPage';
export { ClaimPage } from './ClaimPage';
export { DashboardPage } from './DashboardPage';
export { ForgotPasswordPage } from './ForgotPasswordPage';
export { BookingPage } from './BookingPage';
export { BookingsPage } from './BookingsPage';
export { CheckoutPage } from './CheckoutPage';
export { CheckoutConfirmationPage } from './CheckoutConfirmationPage';
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage';
export { default as TermsPage } from './TermsPage';
